server:
  servlet:
    context-path: /jeysine/admin
    session:
      timeout: 3600s
  port: 9090

spring:
  profiles:
    active: dev
  redis:
    host: 39.108.91.164
    port: 63790
    database: 0
    jedis:
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 20
    password: H89ZB$p1il5G@m*6
    timeout: 30s
  jeysine:
    datasource:
      url: jdbc:postgresql://39.108.251.110:54320/hotchpotch
      username: postgres
      password: H89ZB$p1il5G@m*6
      driver-class-name: org.postgresql.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      #阿里DruidDataSource配置
      druid:
        initialSize: 5
        minIdle: 5
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMills: 300000
        validationQuery: SELECT version
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        #配置监控统计拦截的filters，去掉后监控界面sql无法统计，“wall”用于防火墙
        filters: stat,wall,log4j
        maxPoolPreparedStatementPerConnectionSize: 100
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 39.108.251.110:9300

logging:
  pattern:
    level: info